### PR TITLE
Upgrade to Dropwizard 1.0.0-rc2 and Flyway 4.0

### PR DESCRIPTION
**Pull request by msteinhoff**
Compile and Test reported no errors and it seems to work with my service.

### CODE REVIEW

**Comment by msteinhoff** [comment]
@joschi Any chance to merge this in the next days?

**Comment by msteinhoff** [comment]
Flyway 4.0.1 was released today with a lot of bugfixes, we might as well use that version.

Any objections?

**Comment by joschi** [comment]
@msteinhoff Thanks for this PR!

I'll update the project in 2 separate steps (one upgrading to Flyway 4.x and one upgrading to Dropwizard 1.0.x) instead of doing both things in the same commit.

**Comment by msteinhoff** [comment]
Sure, go ahead :)

As a side note, you might want to add a `.java-version` file to the project root with the contents `1.7`.

That way, users of jEnv (e.g. me :-)) will have automatic java version switching.

**Pull request closed without merging**
